version: '3'

services:
    web:
      image: nginx:latest
      ports:
          - "9090:80"
      volumes:
          - ./client:/app
          - ./default.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
    php:
      image: php:7-fpm
      volumes:
        - ./client:/app
    server:
      build: ./server
      volumes:
        - ./server:/usr/src/app